swagger: '2.0'
info:
  title: Monit API
  description: API for monitoring reports
  version: 1.0
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /:
    get:
      summary: Get API version
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              version:
                type: string

  /usage:
    get:
      summary: Get API usage information
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              usage:
                type: object
                properties:
                  get:
                    type: object
                    properties:
                      /reports:
                        type: string
                      /reports/<string:ID>:
                        type: string
                      /reports/avg/<int:hours>:
                        type: string
                      /reports/last:
                        type: string
                      /reports/list:
                        type: string

  /reports/list:
    get:
      summary: Get all reports names
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              reports:
                type: array
                items:
                  type: string

  /reports/last:
    get:
      summary: Get last report content
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              report:
                type: object 

  /reports:
    get:
      summary: Get all reports content
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              reports:
                type: array
                items:
                  type: object  

  /reports/{ID}:
    get:
      summary: Get report content by ID
      parameters:
        - in: path
          name: ID
          required: true
          type: string
      responses:
        200:
          description: Successful response
          schema:
            type: object
        404:
          description: Report not found

  /reports/avg/{hours}:
    get:
      summary: Get average of reports younger than hours
      parameters:
        - in: path
          name: hours
          required: true
          type: integer
      responses:
        200:
          description: Successful response
          schema:
            type: object 
        404:
          description: No reports found for this period

  /check:
    get:
      summary: Create a new report
      responses:
        200:
          description: Successful response
          schema:
            type: object  

  /api/doc:
    get:
      summary: Swagger UI endpoint
      description: Swagger UI endpoint