swagger: '2.0'
info:
  title: Monit API
  description: API for monitoring reports
  version: 1.0
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

paths:
  /:
    get:
      summary: Get API version
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              version:
                type: string
  
  /reports:
    get:
      summary: Get all reports
      responses:
        200:
          description: Successful response
          schema:
            type: object
  
  